services: 
  mqtt_broker: 
    image: eclipse-mosquitto 
    container_name: mqtt_mosquitto 
    ports: 
      - "1883:1883"
      - "9005:9005"
    volumes: 
      - ./VolumesMosquitto/config:/mosquitto/config 
      - ./VolumesMosquitto/data:/mosquitto/data 
      - ./VolumesMosquitto/log:/mosquitto/log 

  mqtt_clientweb:
    image: emqx/mqttx-web 
    container_name: mqtt_mqttx-web 
    ports:
      - "8082:80"
    depends_on: 
      - mqtt_broker

  portainer: 
    image: portainer/portainer-ce:alpine 
    container_name: mqtt_portainer 
    command: -H unix:///var/run/docker.sock 
    ports: 
      - "8083:9000" 
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock" 
      - "portainer_data:/data" 
    restart: always 

  mqtt_logger: 
    image: eclipse-mosquitto 
    depends_on: 
      - mqtt_broker 
    entrypoint: > 
      sh -c 'sleep 2 && mosquitto_sub -h mqtt_broker -t "#" -v >> /mosquitto/log/messages.log' 
    volumes: 
      - ./VolumesMosquitto/log:/mosquitto/log 

  mqtt_logweb: 
    image: node:20-slim 
    container_name: mqtt_logweb 
    volumes: 
      - ./VolumesMosquitto/log:/log 
      - ./VolumesServeurWebLog/www:/app/www 
      - ./VolumesServeurWebLog/server.js:/app/server.js 
      - ./VolumesServeurWebLog/package.json:/app/package.json 
    working_dir: /app 
    command: sh -c "npm install && node server.js" 
    ports: 
      - "8084:80" 
 
volumes: 
  portainer_data: 